spring.application.name=backend
# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://mysql-20b99489-javitmdfe-5d12.g.aivencloud.com:25197/focus_up?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_i12VpUel9BS_WFdswdC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG